name: Reusable - Close invalid PRs

on:
  workflow_call:
    inputs:
      protected-branch:
        description: "Branch name that must not be used as PR source from forks"
        required: false
        type: string
        default: "main"
      comment:
        description: "Comment posted before closing the PR"
        required: false
        type: string
        default: "Please do not open pull requests from the default branch, create a feature branch instead."

jobs:
  close:
    name: Close invalid PR
    if: ${{ github.repository != github.event.pull_request.head.repo.full_name && github.head_ref == inputs.protected-branch }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: superbrothers/close-pull-request@v3
        with:
          comment: ${{ inputs.comment }}
